### ISSUE TITLE
`CARGO_TARGET_DIR` -> `--target-dir`?

### ISSUE THREAD

**Issue by smoelius** [taiki-e/cargo-llvm-cov#100]
Would you be open to using `cargo`'s `--target-dir` command line option instead of the `CARG_TOARGET_DIR` environment variable?
https://github.com/taiki-e/cargo-llvm-cov/blob/4ab165ff683eb8a1968919ab645aac7c3558850e/src/main.rs#L184
The problem with using the environment variable is that it "infects" subordinate `cargo` invocations. I would expect that in most situations, one would only want to set the target directory for the initial invocation.

I could submit a PR if you like.

**Comment by taiki-e** [comment]
The current behavior is intentional, but I'm fine with changing this.

If you change this, you also need to change the following `ws.target_dir` to `ws.metadata.target_directory`.

https://github.com/taiki-e/cargo-llvm-cov/blob/4ab165ff683eb8a1968919ab645aac7c3558850e/src/main.rs#L327
https://github.com/taiki-e/cargo-llvm-cov/blob/4ab165ff683eb8a1968919ab645aac7c3558850e/src/main.rs#L336
https://github.com/taiki-e/cargo-llvm-cov/blob/4ab165ff683eb8a1968919ab645aac7c3558850e/src/clean.rs#L138

**Comment by smoelius** [comment]
Could you help me to understand why?

**Comment by taiki-e** [comment]
> But I would also be interested to hear why the current behavior is intentional.

cargo will rebuild all dependencies when rustflags is changed.
This is a pain if we run both coverage and normal tests locally, because we will have to rebuild all dependencies frequently.

We can work around this problem by setting a different target directory for each rustflangs, because cargo will only refer to previous rustflangs from builds of the same profile that use the same target directory.

Testing tools such as trybuild have the same problem because they call cargo internally, but there seems to be no way to tell them the location of the target directory we expect other than an environment variable.

The current way works well for my use case, but there seem to be cases where it does not seem to work well, so adding an option to change the behavior or changing the default behavior would be fine.

**Comment by smoelius** [comment]
> Testing tools such as trybuild have the same problem because they call cargo internally, but there seems to be no way to tell them the location of the target directory we expect other than an environment variable.

Aaah. Thank you for the explanation. I'll try to get a PR together.
