### ISSUE TITLE
Add support for code coverage in C/C++ code linked in to Rust library

### ISSUE THREAD

**Issue by scouten-adobe** [taiki-e/cargo-llvm-cov#192]
I'd like to be able to monitor coverage in C++ code that is associated with a Rust crate. Is this possible?

A naive attempt at this (and an example of what I'm hoping to accomplish) is here: https://github.com/adobe/xmp-toolkit-rs/pull/64.

Would appreciate any tips that might make this viable.

**Comment by taiki-e** [comment]
I think this can be handled by using clang&llvm installed in the system instead of llvm bundled with rustc.

IIUC, at least the following two features need to be implemented on the cargo-llvm-cov side:

- Option to specify custom llvm-cov/llvm-profdata paths.
- Option to add/set `-fprofile-instr-generate -fcoverage-mapping` to CFLAGS_/CXXFLAGS_<target> env vars.

**Comment by taiki-e** [comment]
Ok, I've confirmed that the above way works. However, caution is needed regarding the LLVM/clang version. (Incompatible versions will result in an error.)
<img width="591" alt="ffi" src="https://user-images.githubusercontent.com/43724913/179451968-5b94470b-c74e-4b9f-b282-e3c2b1fc0132.png">
