### ISSUE TITLE
Print a summary when outputting to file?

### ISSUE THREAD

**Issue by jaskij** [taiki-e/cargo-llvm-cov#399]
As I mentioned in #398 , I want to integrate these coverage reports with my GitLab CI. Besides simply putting things into place, there is one thing I'm missing.

When running test with coverage, I want `cargo-llvm-cov` to output a summary. This is so that GitLab can grab it, and display the data in the UI. For whatever reason, it will not do so from Cobertura reports.

What GitLab does is extract a single number from the job output using regex, so it's pretty free form. One possible option would be to add a flag that re-enables the summary table which is printed when no other output is enabled.

**Comment by taiki-e** [comment]
Previously, summary output was printed even with other formats, but currently disabled because it cannot provide consistent output with summaries in other types of reports (https://github.com/taiki-e/cargo-llvm-cov/issues/43).

To support this to the extent currently supported by LLVM, it would be reasonable to output multiple formats explicitly.
See https://github.com/taiki-e/cargo-llvm-cov/issues/60 for more on that topic.

Closing in favor of these issues.
