### ISSUE TITLE
Highlight covered lines green in html report

### ISSUE THREAD

**Issue by Warwolt** [taiki-e/cargo-llvm-cov#86]
First of all, really nice project! I got it installed and running in my Windows environment with zero hassle. 👏

I've only used `gcov` in C++ based projects before, and so I've only seen that classical blocky html report. Gcov seems to render covered lines in green, and non-covered lines in red, in their html reports. As far as I can tell for the rust code that I've tested `cargo-llvm-cov` with, I'm only getting red lines.

![image](https://gcovr.github.io/_images/screenshot-html-details.example.cpp.png)
![image](https://user-images.githubusercontent.com/23612880/131578361-28135b4a-960e-4c9c-8805-e3a6dd336996.png)

Is it possible for `cargo-llvm-cov` to generate html reports that contain these green lines? Or does it already and I'm just perhaps having a config issue?

**Comment by taiki-e** [comment]
I think this is because llvm-cov supports region coverage and [branch coverage](#8). (Note: It's llvm-cov that actually provides the functionality to generate the report, and cargo-llvm-cov just calls it with the appropriate flags.)

codecov and others represent partial coverage as a yellow line, but it's not clear which regions are not covered. The following is an example of llvm-cov region coverage.

<img width="339" alt="llvm-cov" src="https://user-images.githubusercontent.com/43724913/149861885-e9ac03e2-fa63-4d73-bc15-7b7841c3992c.png">


Also, if you want to see a line-style coverage report locally, I guess you can use [lcov's html report](https://wiki.documentfoundation.org/Development/Lcov#Generate_HTML_reports.) (cargo-llvm-cov supports the lcov format).

**Comment by taiki-e** [comment]
FYI, I believe that by using [llvm-cov-pretty](https://github.com/dnaka91/llvm-cov-pretty) together, you will get the report with the design you want.
